num1 = int(input("Please enter a number: "))
num2 = int(input("Please enter a second number: "))
num3 = int(input("Please enter a third number: "))
calculation = num1 + num2 + num3
print("the sum of all the numbers = " + str(calculation))
calculation2 = num1 - num2
print("The first number minus the second = " + str(calculation2))
calculation3 = num3 * num1
print("the third number multiplied by the first = " + str(calculation3))
calculation4 = calculation / num3
print("the sum of all numbers divided by the third number =" + str(calculation4))
